sudo: required

language: bash

services:
  - docker

matrix:
  include:
    - env: "3.8"
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/3.8
        - docker build -t bcit/alpine:3.8 .
        - docker run --name ${TRAVIS_COMMIT}-3.8 -d bcit/alpine:3.8 /bin/sh -c "tail -f /dev/null"
        - docker ps -a
      script:
        - docker exec ${TRAVIS_COMMIT}-3.8 /bin/sh -c "cat /etc/os-release"
    - env: "3.9"
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/3.9
        - docker build -t bcit/alpine:3.9 .
        - docker run --name ${TRAVIS_COMMIT}-3.9 -d bcit/alpine:3.9 /bin/sh -c "tail -f /dev/null"
        - docker ps -a
      script:
        - docker exec ${TRAVIS_COMMIT}-3.9 /bin/sh -c "cat /etc/os-release"
    - env: "3.10"
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/3.10
        - docker build -t bcit/alpine:3.10 .
        - docker run --name ${TRAVIS_COMMIT}-3.10 -d bcit/alpine:3.10 /bin/sh -c "tail -f /dev/null"
        - docker ps -a
      script:
        - docker exec ${TRAVIS_COMMIT}-3.10 /bin/sh -c "cat /etc/os-release"
    - env: "3.11"
      before_script:
        - cd ${TRAVIS_BUILD_DIR}/3.11
        - docker build -t bcit/alpine:3.11 .
        - docker run --name ${TRAVIS_COMMIT}-3.11 -d bcit/alpine:3.11 /bin/sh -c "tail -f /dev/null"
        - docker ps -a
      script:
        - docker exec ${TRAVIS_COMMIT}-3.11 /bin/sh -c "cat /etc/os-release"
on:
  branch: master
