sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t bcit/alpine .
  - docker run -n $TRAVIS_COMMIT -d bcit/alpine /bin/sh -c "tail -f /dev/null"
  - docker ps -a

script:
  - docker exec $TRAVIS_COMMIT /bin/sh -c "cat /etc/os-release"
