FROM alpine:<%= parent_tag %>
LABEL maintainer="<%= maintainer %>"

ENV RUNUSER none
ENV HOME /

RUN apk upgrade --no-cache
RUN apk add --no-cache \
        tini

# Add docker-entrypoint script base
ENV DE_VERSION v<%= de_version %>
ADD https://github.com/itsbcit/docker-entrypoint/releases/download/${DE_VERSION}/docker-entrypoint.tar.gz /docker-entrypoint.tar.gz
RUN tar zxvf docker-entrypoint.tar.gz && rm -f docker-entrypoint.tar.gz
RUN chmod -R 555 /docker-entrypoint.*


# Allow resolve-userid.sh script to run
RUN chmod 664 /etc/passwd /etc/group /etc/shadow \
 && chown 0:0 /etc/shadow \
 && chmod 775 /etc

ENTRYPOINT ["/sbin/tini", "--", "/docker-entrypoint.sh"]
<% if tag.include? "supervisord" %>
# Install & configure supervisor
RUN apk add --no-cache \
    supervisor && \
    mkdir -p /var/log/supervisor && \
    mkdir -p /etc/supervisor/conf.d
COPY supervisor.conf /etc/supervisor.conf

CMD ["supervisord", "-c", "/etc/supervisor.conf"]
<% end %>
