FROM alpine:<%= image.version %>

<%= snippet('labels', binding) -%>

ENV TZ America/Vancouver
ENV RUNUSER none
ENV HOME /

RUN apk upgrade --no-cache

<%= snippet('docker-entrypoint', binding) -%>

<%= snippet('dockerize', binding) -%>

<%= snippet('tini', binding) -%>

ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]

RUN apk add --no-cache \
        rsync \
        tzdata \ 
 && ln -svf "/usr/share/zoneinfo/${TZ}" /etc/localtime \
 && echo "${TZ}" > /etc/timezone \
 && chmod 664 /etc/timezone /etc/localtime
<% if image.variant == 'supervisord' -%>

# Install & configure supervisor
RUN apk add --no-cache \
        supervisor \
 && mkdir -p /var/log/supervisor \
 && mkdir -p /etc/supervisor/conf.d
COPY supervisor.conf /etc/supervisor.conf

CMD ["supervisord", "-c", "/etc/supervisor.conf"]
<% end -%>
